#!/usr/bin/perl
#
# FSC Perl STDF Libraries
#
# Confidential Property of Fairchild Semiconductor Corperation
# (c) Copyright Fairchild Semiconductor Corperation, 1999
# All rights reserved
#
# MODIFICATION HISTORY:
#
# DATE       WHO             DESCRIPTION
# __________ ______________  __________________________________________________
# 11-02-1999 Steve Frampton  Original.  Contact Information:
#                            (207) 273-3364
#                            sframpto@fairchildsemi.com,
#                            sframpto@midcoast.com
# 02-09-2000 Steve Frampton  Added ignore_gdr_pads option
# 02-14-2000 Steve Frampton  Added use Carp within package
# 10-10-2000 Steve Frampton  Changed stdf_copy to use stdfPL_current.spec
# 01-02-2001 Steve Frampton  Added documentation for -require option
#                            for write_stdf_dump_WMR.pl
# 04-15-2006 Steve Frampton  Added documentation for -require option
#
# 04-18-2006 Steve Frampton  Added strip_bin option so that ascii output can be #                            diff'd (SPEC_REV null chars).
# 08-06-2006 Steve Frampton  Added pattern match option for record
# 01-03-2013 Scott Boothby   Read file into internal data structures that match the file version, instead of reading into the latest spec.
$useage = '
Copy an STDF V4 or STDF+ file to ascii, hex, or binary formats

stdf_copy [-ascii|-hex|-binary] [-strip_bin] [-ignore_gdr_pads] [-require perl_code_file] -match REGEX pattern [input_file [output_file]]

OPTIONS
  If not options are specified, -ascii is the default.
  -ascii
     Dump file in format similar to stdf_dump utility.
     Leaves date as integer.  Flags are in binary.
  -hex
     Reads file record by record.  Each record is output in
     a hexadecimal format.  Useful for debugging bad files.
  -binary
     Copies file record by record.  Useful to convert a
     file from one platform to another.
  -ignore_gdr_pads
     GDR records are unpacked and printed without pad bytes.
  -strip_bin
     Strip out binary characters, eg emir.spec_rev
  -require perl_code_file
     Loads custom perl code into the in namespace using perl
     require pragma.  Intended as a way for users to write
     custom output routines.  See write_stdf_dump_WMR.pl for an example.
     (write_stdf_dump_WMR.pl will output the same as the stdf
     programmers C libraryies stdf_dump).
  -match pattern
     Prints records that match the specified REGEXP pattern.
     -ascii mode only.     

ARGUMENTS
  input_file STDF V4 or + input file name.  If - is specified,
             input file is stdin.

  output_file Output file.  If - is specified, output file is
              stdout.  If not specified output file is stdout.

  if input_file and output_file are not specified, then stdin
  and stdout are used.


BUGS/LIMITATIONS
  These limitations apply to library, not just this utility.

  VMS Limitations
    Real numbers do not work for VMS files when running on a platform
    other than VMS.  Not tested under VMS.  Not well tested with VMS files.
  GDR Record is not implimented.
  Arrays are not implimented.

' ;
#
# A capability that was deleted, because of the performance impact
# on stdf_unpack as well as inconsistencies of defining Infinity
# on the different target platforms.
# Flag is still set within stdf_copy, but stdf_unpack ignores it.
#
$old_option = '
  -fix_real
     Converts Infinity as defined by IEEE to MAX_FLT
     Converts -Infinity as defined by IEEE to -MAX_FLT
     Converts NaN as defined by IEEE to 0
     Please reference fpclass_t within /usr/include/ieeefp.h
' ;

#
# Load libraries
#
use Carp ;  # error messages - does not work within stdf_use.pl
# set path to executable for libraries
use English ; # use intellegent variable names
use FindBin ; 
use lib "$FindBin::Bin" ; # set up path for libraries the same as script
use lib $ENV{'STDF_PERL_LIB'} ; # look for libraries in this directory

require "stdf_use.pl" ;   # libraries that are not generated

$format = "ascii" ;
$record_number = 0 ;
$strip_bin = 0 ;
$out_regex = undef ;
while (substr($ARGV[0],0,1) eq '-')
  {
  my $arg = substr($ARGV[0],1) ;
  if ( $arg =~ /ascii|binary|hex/ )
     { $format = $arg ; shift ; }
  elsif ($arg eq 'ignore_gdr_pads')
     { $ignore_gdr_pads = 1 ; shift ; }
  elsif ($arg eq 'fix_real')
     { $fix_bad_float = 1 ; shift ; }  # global used by stdf_unpack
  elsif ($arg eq 'strip_bin')
     { $strip_bin = 1 ; shift ; }  # global used by stdf_unpack
  elsif ($arg eq 'h')
     { print $useage; exit; }
  elsif ($arg eq 'require')
     {
     shift;
     $require= shift ;
     }
  elsif ($arg eq 'match')
     {
     shift ;
     $out_regex = shift ;
     }
  else
     { confess "-$arg is not a valid argument\n" ; }
  }
if ($ARGV[0] && !($ARGV[0] eq '-'))
  {
  $in_fn = shift ;
  open INPUT, "<$in_fn" or confess "Could not open $in_fn\n" ;
  }
else
  {
  $in_fn = '-' ;
  open INPUT, "<&STDIN" or confess 'Could not open STDIN\n' ;
  }
binmode INPUT ; # open file in binary, required for MSDOS

if ($ARGV[0] && !($ARGV[0] eq '-') )
  {
  $out_fn = shift ;
  if ($out_fn eq $in_fn)
    { confess "Input and Output file names are the same\n" ; }
  open OUTPUT, ">$out_fn" or confess "Could not open $out_fn\n" ;
  }
else
  {
  $out_fn = '-' ;
  open OUTPUT, ">&STDOUT" or confess "Could not open STDOUT\n" ;
  }

if ($format eq 'binary')
  {
  binmode OUTPUT ;  # only required for MSDOS
  }

open LOG, ">&STDERR" or confess "Could not open STDERR\n" ;
#
# read first record
# '< fix vim
($status, $rec_len, $rec_typ, $rec_sub, $buf) = read_first_rec( \*INPUT, $stdf_ver ) ;
$total_bytes_read = $status ;
#
# check the version and load a specification
# as well as custom coded routines.
# the input specification is also used for the 
# output specification
#
if ($stdf_ver==4) 
  {
  $in_spec='stdfV4';
  $in_gen=$in_spec;
  }
elsif ($stdf_ver ==3)
  {
  $in_spec='stdfV3';
  $in_gen=$in_spec;
  }
elsif ($stdf_ver==104)
  {
  $in_spec='stdfPL_104' ;
  $in_gen=$in_spec;
  }
elsif ($stdf_ver > 104)
  {
  $in_spec='stdfPL_current' ;
  $in_gen="stdfPL_" . $stdf_ver ;
  }
else
  {
  warn "Don't have a spec file for stdf version: $stdf_ver" ;
  $in_spec='' ;
  }
if (defined($in_spec))
  {
  package in ;
  use Carp ;
  $eval_str=&::generate_all($::in_gen.".spec" ) ; #" generated stdf code
  $eval_rc = eval $eval_str ;
  if (!defined($eval_rc))
    { confess $@ ; }
require $::in_spec.'.pl' ; # custom stdf code, may over-ride.
#require '/tmp/foo.pl' ;
  if ( defined($::require))
    {
    require $::require ; # user specified custom stdf code, may over-ride 
    }

  }
#
# continue processing file
#
$write = 'stdf_write_'.$format ;
while ( $status )
  {
  # call either stdf_write_hex, stdf_write_ascii, or stdf_write_binary
  $record_number++ ;
  &{$write}( $total_bytes_read, $rec_len, $rec_typ, $rec_sub, $buf, \*OUTPUT, $record_number, $out_regex ) ;
  ($status, $rec_len, $rec_typ, $rec_sub, $buf) = read_rec( \*INPUT, $stdf_ver ) ;
  $total_bytes_read += $status ;
  }

