class unit_level_data:

	def __init__(
				self, 
				unitid : str, 
				device_num : str, 
				wire_num : str, 
				bond_num : str, 
				grp_id : str,
				LEADFRAME : str,
				bond_group_id : str,
				wire_feed : str,
				bond_start_time : str,
				bond_ramp_time : str,
				bond_hold_time : str,
				bond_start_power : str,
				bond_ramp_power : str,
				bond_hold_power : str,
				bond_start_force : str,
				bond_ramp_force : str,
				bond_hold_force: str,
				BPM_PEAK_STATUS : str,
				BPM_US_STATUS : str,
				BPM_DEFORM_STATUS : str,
				BPM_FREQUENCY_STATUS : str,
				ALC_PULLTEST_STATUS : str,
				lower_lim : str,
				upper_lim : str,
				target_lim : str,
				time_readpoint : str,
				wedge_change : str,
				guide_change : str,
				wedge_screw : str,
				small_tube : str,
				large_tube : str
				 ):
		self.dbcid = unitid
		self.device_num = device_num
		self.wire_num = wire_num
		self.bond_num = bond_num
		self.grp_id = grp_id
		self.measurements = {}
		self.LEADFRAME = LEADFRAME
		self.wire_feed = wire_feed
		self.bond_start_time = bond_start_time
		self.bond_ramp_time = bond_ramp_time
		self.bond_hold_time = bond_hold_time
		self.bond_start_power = bond_start_power
		self.bond_ramp_power = bond_ramp_power
		self.bond_hold_power = bond_hold_power
		self.bond_start_force = bond_start_force
		self.bond_ramp_force = bond_ramp_force
		self.bond_hold_force = bond_hold_force
		self.BPM_PEAK_STATUS = BPM_PEAK_STATUS
		self.BPM_DEFORM_STATUS = BPM_DEFORM_STATUS
		self.BPM_US_STATUS = BPM_US_STATUS
		self.BPM_FREQUENCY_STATUS = BPM_FREQUENCY_STATUS
		self.ALC_PULLTEST_STATUS = ALC_PULLTEST_STATUS
		self.BOND_POSITION_X = ''
		self.BOND_POSITION_Y = ''
		self.BOND_POSITION_Z = ''
		self.BOND_POSITION_T = ''
		self.lower_limit = lower_lim
		self.upper_limit = upper_lim
		self.target_limit = target_lim
		self.time_readpoint = time_readpoint
		self.wedge_change = wedge_change
		self.guide_change = guide_change
		self.wedge_screw  = wedge_screw 
		self.small_tube = small_tube
		self.large_tube = large_tube