-- DDL for pipeline_runs table
-- Recommended for Oracle 12c+

CREATE TABLE pipeline_runs (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  start_local TIMESTAMP WITH TIME ZONE NOT NULL,
  end_local   TIMESTAMP WITH TIME ZONE NOT NULL,
  start_utc   TIMESTAMP WITH TIME ZONE NOT NULL,
  end_utc     TIMESTAMP WITH TIME ZONE NOT NULL,
  elapsed_seconds NUMBER(12,3) NOT NULL,
  elapsed_human   VARCHAR2(256) NOT NULL,
  output_file     VARCHAR2(1024) NOT NULL,
  rowcount        NUMBER(12) NOT NULL,
  log_file        VARCHAR2(1024) NOT NULL,
  pid             NUMBER(10) NOT NULL,
  date_code       VARCHAR2(64) NOT NULL,
  pipeline_name   VARCHAR2(255),
  script_name     VARCHAR2(255),
  pipeline_type   VARCHAR2(100),
  environment     VARCHAR2(50),
  archived_file   VARCHAR2(1024),
  output_file_gen     VARCHAR2(1024),
  output_files_gen    CLOB,
  output_file_trace   VARCHAR2(1024),
  output_files_trace  CLOB,
  archived_gen_files  CLOB,
  archived_trace_files CLOB,
  rows_extracted      NUMBER(12),
  rows_written        NUMBER(12),
  total_files         NUMBER(5),
  out_files           CLOB,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

-- Indexes
CREATE INDEX idx_pipeline_runs_start_utc ON pipeline_runs(start_utc);
CREATE INDEX idx_pipeline_runs_pipeline_name ON pipeline_runs(pipeline_name);
CREATE INDEX idx_pipeline_runs_date_code ON pipeline_runs(date_code);
CREATE INDEX idx_pipeline_name_start_utc ON pipeline_runs(pipeline_name, start_utc);

-- Optional: sequence for older Oracle versions
-- CREATE SEQUENCE pipeline_runs_seq START WITH 1 INCREMENT BY 1;

-- Migration script for existing tables (add new columns for row tracking):
-- ALTER TABLE pipeline_runs ADD (rows_extracted NUMBER(12));
-- ALTER TABLE pipeline_runs ADD (rows_written NUMBER(12));
-- ALTER TABLE pipeline_runs ADD (total_files NUMBER(5));
-- ALTER TABLE pipeline_runs ADD (out_files CLOB);

-- Example insert (use bind variables):
-- INSERT INTO pipeline_runs (
--   start_local, end_local, start_utc, end_utc,
--   elapsed_seconds, elapsed_human, output_file, rowcount, log_file,
--   pid, date_code, pipeline_name, script_name, pipeline_type, environment, archived_file,
--   rows_extracted, rows_written, total_files, out_files
-- ) VALUES (
--   :start_local, :end_local, :start_utc, :end_utc,
--   :elapsed_seconds, :elapsed_human, :output_file, :rowcount, :log_file,
--   :pid, :date_code, :pipeline_name, :script_name, :pipeline_type, :environment, :archived_file,
--   :rows_extracted, :rows_written, :total_files, :out_files
-- );
