/*
** MODIFICATION HISTORY:
**
** Date        Who            Comment
** ----------- -------------- ------------------
** 25-Nov-2020 S. Boothby     Created.
*/
  CREATE TABLE "REFDB"."PP_LOT" 
   (	"LOT" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"PARENT_LOT" VARCHAR2(32 BYTE), 
	"PRODUCT" VARCHAR2(32 BYTE), 
	"LOT_OWNER" VARCHAR2(32 BYTE), 
	"PARENT_PRODUCT" VARCHAR2(32 BYTE), 
	"SOURCE_LOT" VARCHAR2(32 BYTE), 
	"INSERT_TIME" DATE DEFAULT sysdate, 
	 PRIMARY KEY ("LOT")
   ) 
  TABLESPACE "DP_DATA" ;

  CREATE INDEX "REFDB"."I_PP_LOT_01" ON "REFDB"."PP_LOT" ("INSERT_TIME") 
  TABLESPACE "DP_INDX" ;

  CREATE UNIQUE INDEX "REFDB"."LOT_PROD" ON "REFDB"."PP_LOT" ("LOT", "PRODUCT") 
  TABLESPACE "DP_INDX" ;

  CREATE INDEX "REFDB"."REFDB_PP_SRC_LOT_PROD_LOT" ON "REFDB"."PP_LOT" ("SOURCE_LOT", "PRODUCT", "LOT") 
  TABLESPACE "DP_INDX" ;

  CREATE INDEX "REFDB"."SOURCE_LOT" ON "REFDB"."PP_LOT" ("SOURCE_LOT") 
  TABLESPACE "DP_INDX" ;

  CREATE INDEX "REFDB"."SRC_LOT_PROD" ON "REFDB"."PP_LOT" ("SOURCE_LOT", "PRODUCT") 
  TABLESPACE "DP_INDX" ;

  CREATE TABLE "REFDB"."PP_FINALLOT" 
   (	"LOT" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"LOT_OWNER" VARCHAR2(32 BYTE), 
	"PRODUCT" VARCHAR2(32 BYTE), 
	"DATE_CODE" VARCHAR2(32 BYTE), 
	"INSERT_TIME" DATE DEFAULT sysdate, 
	 PRIMARY KEY ("LOT")
   )
  TABLESPACE "DP_DATA" ;

  CREATE INDEX "REFDB"."DC_FINALLOT_02" ON "REFDB"."PP_FINALLOT" ("DATE_CODE") 
  TABLESPACE "DP_INDX" ;

  CREATE UNIQUE INDEX "REFDB"."FLLOT_PROD" ON "REFDB"."PP_FINALLOT" ("LOT", "PRODUCT") 
  TABLESPACE "DP_INDX" ;

  CREATE INDEX "REFDB"."I_PP_FINALLOT_01" ON "REFDB"."PP_FINALLOT" ("INSERT_TIME") 
  TABLESPACE "DP_INDX" ;

  CREATE INDEX "REFDB"."PROD_FLLOT" ON "REFDB"."PP_FINALLOT" ("PRODUCT", "LOT") 
  TABLESPACE "DP_INDX" ;



  CREATE TABLE "REFDB"."PP_PROD" 
   (	"PRODUCT" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"ITEM_TYPE" VARCHAR2(15 BYTE), 
	"FAB" VARCHAR2(32 BYTE), 
	"FAB_DESC" VARCHAR2(50 BYTE), 
	"AFM" VARCHAR2(45 BYTE), 
	"PROCESS" VARCHAR2(32 BYTE), 
	"FAMILY" VARCHAR2(32 BYTE), 
	"PACKAGE" VARCHAR2(32 BYTE), 
	"GDPW" NUMBER(38,0), 
	"WF_UNITS" VARCHAR2(32 BYTE), 
	"WF_SIZE" FLOAT(126), 
	"DIE_UNITS" VARCHAR2(32 BYTE), 
	"DIE_WIDTH" FLOAT(126), 
	"DIE_HEIGHT" FLOAT(126), 
	"INSERT_TIME" DATE DEFAULT sysdate, 
	 PRIMARY KEY ("PRODUCT")
   ) 
  TABLESPACE "DP_DATA" ;

  CREATE INDEX "REFDB"."I_PP_PROD_01" ON "REFDB"."PP_PROD" ("INSERT_TIME") 
  TABLESPACE "DP_INDX" ;

  CREATE INDEX "REFDB"."REFDB_PP_PROD_FAB_PROD" ON "REFDB"."PP_PROD" ("FAB_DESC", "PRODUCT") 
  TABLESPACE "DP_INDX" ;

  CREATE INDEX "REFDB"."REFDB_PP_PROD_FAMILY_PROD" ON "REFDB"."PP_PROD" ("FAMILY", "PRODUCT") 
  TABLESPACE "DP_INDX" ;

  CREATE INDEX "REFDB"."REFDB_PP_PROD_PKG_PROD" ON "REFDB"."PP_PROD" ("PACKAGE", "PRODUCT") 
  TABLESPACE "DP_INDX" ;

  CREATE INDEX "REFDB"."REFDB_PP_PROD_PROC_PROD" ON "REFDB"."PP_PROD" ("PROCESS", "PRODUCT") 
  TABLESPACE "DP_INDX" ;



  CREATE TABLE "REFDB"."PP_LIMITS" 
   (	"PROGRAM" VARCHAR2(128 BYTE) NOT NULL ENABLE, 
	"REVISION" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"START_TIME" DATE, 
	"PP_SCRIPT" VARCHAR2(256 BYTE), 
	"LIMIT_FILE" VARCHAR2(256 BYTE), 
	"INPUT_FILE" VARCHAR2(256 BYTE), 
	"INSERT_TIME" DATE DEFAULT sysdate, 
	 PRIMARY KEY ("PROGRAM", "REVISION")
   ) 
  TABLESPACE "DP_DATA" ;

  CREATE INDEX "REFDB"."I_PP_LIMITS_01" ON "REFDB"."PP_LIMITS" ("INSERT_TIME") 
  TABLESPACE "DP_INDX" ;


  CREATE TABLE "REFDB"."PP_LOTCLASS" 
   (	"LOT_OWNER" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"LOT_CLASS" VARCHAR2(32 BYTE), 
	"INSERT_TIME" DATE DEFAULT sysdate, 
	 PRIMARY KEY ("LOT_OWNER")
   ) 
  TABLESPACE "DP_DATA" ;

  CREATE INDEX "REFDB"."I_PP_LOTCLASS_01" ON "REFDB"."PP_LOTCLASS" ("INSERT_TIME") 
  TABLESPACE "DP_INDX" ;



  CREATE TABLE "REFDB"."PP_LOG" 
   (	"PP_LOG_ID" RAW(16) DEFAULT SYS_GUID(), 
	"LOT" VARCHAR2(32 BYTE), 
	"ENVIRONMENT" VARCHAR2(32 BYTE), 
	"PROCESS_DATETIME" DATE, 
	"PROCESS_CODE" NUMBER(*,0), 
	"FILE_NAME" VARCHAR2(255 BYTE), 
	"OUTPUT_DIRECTORY" VARCHAR2(32 BYTE), 
	"LOG_MESSAGE" VARCHAR2(2000 BYTE), 
	"INSERT_ID" VARCHAR2(25 BYTE), 
	"MAP_ID" VARCHAR2(25 BYTE), 
	"WAFER_NUM" VARCHAR2(255 BYTE), 
	"ERROR_CODE" VARCHAR2(5 BYTE), 
	"PROGRAM_CLASS" NUMBER, 
	"SITE" VARCHAR2(5 BYTE), 
	"PROCESS_DATETIME_ADJUST" DATE, 
	"LIMIT_FILE_NAME" VARCHAR2(255 BYTE), 
	"PROGRAM_NAME" VARCHAR2(255 BYTE), 
	"EXTENSION" VARCHAR2(100 BYTE), 
	"MD5" VARCHAR2(100 BYTE), 
	"PATH" VARCHAR2(255 BYTE), 
	 PRIMARY KEY ("PP_LOG_ID")
   ) 
  TABLESPACE "DP_DATA" ;

  CREATE INDEX "REFDB"."I_PP_LOG_01" ON "REFDB"."PP_LOG" ("LOT") 
  TABLESPACE "DP_INDX" ;



  CREATE TABLE "REFDB"."LOAD_ERR_CODE" 
   (	"LOAD_ERR_CODE_ID" RAW(16) DEFAULT SYS_GUID(), 
	"ERROR" VARCHAR2(255 BYTE), 
	"ERROR_CODE" VARCHAR2(10 BYTE), 
	 PRIMARY KEY ("LOAD_ERR_CODE_ID")
   ) 
  TABLESPACE "DP_DATA" ;



  CREATE TABLE "REFDB"."LOAD_ERR_LOG" 
   (	"LOAD_ERR_LOG_ID" RAW(16) DEFAULT SYS_GUID(), 
	"LOT" VARCHAR2(100 BYTE), 
	"WAFER_NUM" VARCHAR2(255 BYTE), 
	"ENVIRONMENT" VARCHAR2(32 BYTE), 
	"FILE_NAME" VARCHAR2(255 BYTE), 
	"ERROR_DATETIME" DATE, 
	"INSERT_DATETIME" DATE, 
	"ERR_MESSAGE" VARCHAR2(2000 BYTE), 
	"ERROR_CODE" VARCHAR2(10 BYTE), 
	"PATH" VARCHAR2(255 BYTE), 
	"INSERT_DATETIME_ADJUST" DATE, 
	"PROGRAM_CLASS" NUMBER, 
	"PROGRAM_NAME" VARCHAR2(255 BYTE), 
	"CREATE_IFF_DATETIME" DATE, 
	"ORIG_EXT" VARCHAR2(100 BYTE), 
	"EXT" VARCHAR2(50 BYTE), 
	 PRIMARY KEY ("LOAD_ERR_LOG_ID")
   ) SEGMENT CREATION IMMEDIATE 
  TABLESPACE "DP_DATA" ;

  CREATE INDEX "REFDB"."I_PP_LOAD_ERR_LOG_01" ON "REFDB"."LOAD_ERR_LOG" ("LOT") 
  TABLESPACE "DP_INDX" ;



  CREATE TABLE "REFDB"."PP_WMAP" 
   (	"PRODUCT" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"TESTER_TYPE" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"WF_UNITS" VARCHAR2(8 BYTE), 
	"WF_SIZE" FLOAT(126), 
	"FLAT_TYPE" CHAR(1 BYTE), 
	"FLAT" CHAR(1 BYTE), 
	"DIE_WIDTH" FLOAT(126), 
	"DIE_HEIGHT" FLOAT(126), 
	"CENTER_X" FLOAT(126), 
	"CENTER_Y" FLOAT(126), 
	"POSITIVE_X" CHAR(1 BYTE), 
	"POSITIVE_Y" CHAR(1 BYTE), 
	"RETICLE_ROWS" NUMBER(38,0), 
	"RETICLE_COLS" NUMBER(38,0), 
	"RETICLE_ROW_OFFSET" NUMBER(38,0), 
	"RETICLE_COL_OFFSET" NUMBER(38,0), 
	"CONFIRMED" CHAR(1 BYTE), 
	"DEVICE_COUNT" NUMBER(38,0), 
	"CONFIRM_TIME" DATE, 
	"COMMENTS" VARCHAR2(256 BYTE), 
	"INSERT_TIME" DATE DEFAULT sysdate, 
	"INPUT_FILE" VARCHAR2(256 BYTE), 
	"CFG_ID" NUMBER, 
	"LOCATION" NVARCHAR2(32), 
	"REF_DIE_X" NUMBER, 
	"REF_DIE_Y" NUMBER, 
	"REF_DIE_INIT_DT" DATE, 
	 CONSTRAINT "SYS_C0056614" PRIMARY KEY ("PRODUCT", "TESTER_TYPE", "LOCATION")
   ) 
  TABLESPACE "DP_DATA" ;

  CREATE INDEX "REFDB"."I_PP_WMAP_01" ON "REFDB"."PP_WMAP" ("INSERT_TIME") 
  TABLESPACE "DP_INDX" ;

  CREATE INDEX "REFDB"."I_PP_WMAP_02" ON "REFDB"."PP_WMAP" ("REF_DIE_X", "REF_DIE_Y") 
  TABLESPACE "DP_INDX" ;

-- SET DEFINE OFF; /* Use this in SQL DEVELOPER to stop it from promprint for new_row */
CREATE OR REPLACE EDITIONABLE TRIGGER "REFDB"."UPDATECONFIRMDATE" 
BEFORE UPDATE OF CONFIRMED ON REFDB.PP_WMAP
REFERENCING OLD as old_row NEW as new_row
for each row
BEGIN
  if :new_row.confirmed = '1'
  then
  SELECT sysdate 
    INTO :new_row.confirm_time
    FROM DUAL;
  end if;
END;
/
ALTER TRIGGER "REFDB"."UPDATECONFIRMDATE" ENABLE;



CREATE SEQUENCE  "REFDB"."PP_WMAP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE OR REPLACE EDITIONABLE TRIGGER "REFDB"."PP_WMAP_TRG" BEFORE INSERT ON refdb.pp_wmap FOR EACH ROW
BEGIN
  SELECT refdb.pp_wmap_seq.nextval INTO :new.cfg_id FROM dual;
END;
/
ALTER TRIGGER "REFDB"."PP_WMAP_TRG" ENABLE;

