-- USER SQL
CREATE USER "REFDB"
IDENTIFIED BY "XBfjCq#$1542FFz"
DEFAULT TABLESPACE "DP_DATA"
TEMPORARY TABLESPACE "TEMP"
;

-- QUOTAS
ALTER USER "REFDB" QUOTA UNLIMITED ON "DP_DATA";
ALTER USER "REFDB" QUOTA UNLIMITED ON "DP_INDX";

-- ROLES
--ALTER USER "REFDB" DEFAULT ROLE "IDSUSER_ROLE";
GRANT "IDSUSER_ROLE" to "REFDB";
ALTER USER "REFDB" DEFAULT ROLE "IDSUSER_ROLE";

