/*
** MODIFICATION HISTORY:
**
** Date        Who            Comment
** ----------- -------------- ------------------
** 25-Nov-2020 S. Boothby     Created.
*/
  CREATE TABLE "REFDB"."ON_SLICE" 
   (    "SLICE" VARCHAR2(32 BYTE) NOT NULL,
        "GLOBAL_WAFER_ID" VARCHAR2(32 BYTE),
        "PUCK_ID" VARCHAR2(32 BYTE) NOT NULL,
        "RUN_ID" VARCHAR2(32 BYTE) NOT NULL,
        "SLICE_SOURCE_LOT" VARCHAR2(32 BYTE) NOT NULL,
        "START_LOT" VARCHAR2(32 BYTE),
        "FAB_WAFER_ID" VARCHAR2(32 BYTE),
        "FAB_SOURCE_LOT" VARCHAR2(32 BYTE),
        "SLICE_START_TIME" DATE NOT NULL,
        "SLICE_PARTNAME" VARCHAR2(32 BYTE),
        "SLICE_LOTTYPE" VARCHAR2(8 BYTE),
        "SLICE_SUPPLIERID" VARCHAR2(32 BYTE),
        "PUCK_HEIGHT" INTEGER,
        "SLICE_ORDER" INTEGER,
        "INSERT_TIME" DATE DEFAULT sysdate,
         PRIMARY KEY ("SLICE")
   )
  TABLESPACE "DP_DATA" ;

  CREATE INDEX "REFDB"."REFDB_ON_SLICE_PUCK_ID" ON "REFDB"."ON_SLICE" ("PUCK_ID") 
  TABLESPACE "DP_INDX" ;

  CREATE INDEX "REFDB"."REFDB_ON_SLICE_FAB_WAFER_ID" ON "REFDB"."ON_SLICE" ("FAB_WAFER_ID") 
  TABLESPACE "DP_INDX" ;

  CREATE INDEX "REFDB"."REFDB_ON_SLICE_SOURCE_LOT" ON "REFDB"."ON_SLICE" ("SLICE_SOURCE_LOT") 
  TABLESPACE "DP_INDX" ;

  CREATE INDEX "REFDB"."REFDB_ON_SLICE_START_TIME" ON "REFDB"."ON_SLICE" ("SLICE_START_TIME") 
  TABLESPACE "DP_INDX" ;

  CREATE INDEX "REFDB"."REFDB_ON_GLOBAL_WAFER_ID" ON "REFDB"."ON_SLICE" ("GLOBAL_WAFER_ID") 
  TABLESPACE "DP_INDX" ;
  GRANT SELECT ON REFDB.ON_SLICE TO PUBLIC;
