[webservice]
onlot=http://globmfgapp.onsemi.com:61050/exensioreftables-ws/api/onlot/bylotid/
onprod=http://globmfgapp.onsemi.com:61050/exensioreftables-ws/api/onprod/byproduct/
onscribe=http://globmfgapp.onsemi.com:61050/exensioreftables-ws/api/onscribe/byscribeid/

[retwaf]
dir=/apps/exensio_data/data/efk_wat_keysight/ret_waf
