#!/bin/env perl_db
#
# 23-Feb-2022 Eric A. 	initial release

use strict;
use FindBin::libs;
use PDF::DpData;
use PDF::DpLoad;
use PDF::DAO;
use PDF::Log;
use PDF::DpWriter;
use PDF::Formatter;
use PDF::WS;
use Getopt::Long;
use File::Basename;
use Data::Dumper;
use IO::Uncompress::Gunzip qw(gunzip $GunzipError);
use IO::Uncompress::Unzip qw(unzip $UnzipError);

our $VERSION ="1.0";

my (%hOptions) = ();

if ( $#ARGV < 0 ) {
        print "Usage: $0 <FILENAME> <OPTIONS>\n";
        exit 1;
}
unless (
        GetOptions(
                \%hOptions,  "OUT=s", "LOGFILE=s", "DEBUG", "TRACE", "ALERT" 
        )
)
{
        print "Invalid options.\n";
	exit;
}

my @required_options = qw/OUT/;

if (grep { !exists $hOptions{$_} } @required_options) {
        print "Error! Missing required options.\n";
	exit 1;
}

PDF::Log->init(\%hOptions);

my $infile = $ARGV[0];
my $outdir = $hOptions{OUT};
my $alert = $hOptions{ALERT};
my $enrfile = "";

if ( ! -f $infile ) {
	dpExit(1,"Error! File does not exists.");
}

 
INFO ("Input file = $infile");

my $dcom_file = $infile;
if ($infile =~ /\.gz$/) {
        $dcom_file =~ s/\.gz$//;
	gunzip $infile => $dcom_file or die "gunzip failed: $GunzipError\n";
        INFO ("UnGzipped file = $dcom_file");
}
elsif ($infile =~ /\.zip$/) {
        $dcom_file =~ s/\.zip$//;
	unzip $infile => $dcom_file or die "unzip failed: $UnzipError\n";
        INFO ("UnZipped file = $dcom_file");
}

my $fname = basename $dcom_file;
$enrfile = "${outdir}/${fname}";

my $grpHead = `head $dcom_file`;	#get 4 heaaders
my @arrHead = split /^/, $grpHead;	#split at start of line
my $fileHeader1 = $arrHead[0];
my $fileHeader2 = $arrHead[1];
my $fileHeader3 = $arrHead[2];
my $fileHeader4 = $arrHead[3];;

# validate headers
if ($fileHeader1 !~ /^\#Created on/ig) {
	dpExit(1,"Missing header or header does not match to what is expected");
}
elsif ($fileHeader2 !~ /^\#Generated by WIP Extractor/ig) {
	dpExit(1,"Missing header or header does not match to what is expected");
}
elsif ($fileHeader3 !~ /^\#DataSource\,FormatVersion\,Lot\,Fab\,ProductFamily\,Technology\,Plan\,Product\,CustomerProduct\,SourceLot\,LotLabel\,LotType\,WaferNumber\,Wafer\,OperSequence\,ProcStep\,Stage\,OrigSlot\,FinalSlot\,OrigCass\,FinalCass\,Zone\,ZoneSeat\,ZoneBoat\,Subtool\,Equipment\,TrackInTime\,TrackOutTime\,Recipe\,Operator\,Tooling\,ReworkCount$/ig) {

	dpExit(1,"Missing header or header does not match to what is expected");	
}
elsif ($fileHeader4 !~ /^\#Version Number/ig) {
	dpExit(1,"Missing header or header does not match to what is expected");
}
else {
	INFO("Good! Header found.");
}

chomp $fileHeader1;
chomp $fileHeader2;
chomp $fileHeader3;
chomp $fileHeader4;

my $ln_cnt = 0;
my $technology = "";

open my $in, '<',  $dcom_file or die "Can't read input file: $dcom_file $!";
my $out;
my $fle_cnt = 0;

while(my $line = <$in>) {
	$ln_cnt++;
	my @arr = split /\,/, $line;

	if ($ln_cnt >= 5) {

		$arr[5] =~ s/\"//g;
		$arr[5] = trim($arr[5]);

		if ($technology !~ /$arr[5]/) {
			close $out if $out;
			$technology = trim($arr[5]);
			my $tech_fn = $technology;
			$tech_fn =~ s/\s+//g;

			$fle_cnt++;

			INFO ("Output file = ${enrfile}.${tech_fn}.${fle_cnt}");
	
			open $out, '>', $enrfile.".".$tech_fn.".".$fle_cnt or die "Can't write to split file:$!";

			print $out $fileHeader1,"\n";
			print $out $fileHeader2,"\n";
			print $out $fileHeader3,"\n";
			print $out $fileHeader4,"\n";
			
		}
		print $out $line;
	}


}
close $out;
close $in;

# delete residue extracted files
unlink $dcom_file if $infile =~ /\.zip/i;


dpExit(0);

