#!/bin/env perl_db
#
# 12-Aug-2021 Eric A. 	initial release

use strict;
use FindBin::libs;
use PDF::DpData;
use PDF::DpLoad;
use PDF::DAO;
use PDF::Log;
use PDF::DpWriter;
use PDF::Formatter;
use PDF::WS;
use Getopt::Long;
use File::Basename;
use Data::Dumper;
use IO::Uncompress::Gunzip qw(gunzip $GunzipError);
use IO::Uncompress::Unzip qw(unzip $UnzipError);

our $VERSION ="1.0";

my (%hOptions) = ();

if ( $#ARGV < 0 ) {
        print "Usage: $0 <FILENAME> <OPTIONS>\n";
        exit 1;
}
unless (
        GetOptions(
                \%hOptions,  "OUT=s", "LOGFILE=s", "DEBUG", "TRACE", "ALERT", "ARCHIVE=s", "GZIP", "SPLITBY=i"
        )
)
{
        print "Invalid options.\n";
	exit;
}

my @required_options = qw/OUT ARCHIVE SPLITBY/;

if (grep { !exists $hOptions{$_} } @required_options) {
        print "Error! Missing required options.\n";
	exit 1;
}

PDF::Log->init(\%hOptions);

my $infile = $ARGV[0];
my $outdir = $hOptions{OUT};
my $arcdir = $hOptions{ARCHIVE};
my $alert = $hOptions{ALERT};
my $lnCntSplit = $hOptions{SPLITBY};
my $meta_flg = "Y";
my $agile_flg = "Y";
my $fab = "UV5:GF FISHKILL FE CTI";
my $enrfile = "";
my $arcfile = "";

if ( ! -f $infile ) {
	dpExit(1,"Error! File does not exists.");
}

 
INFO ("Input file = $infile");

my $dcom_file = $infile;
if ($infile =~ /\.gz$/) {
        $dcom_file =~ s/\.gz$//;
	gunzip $infile => $dcom_file or die "gunzip failed: $GunzipError\n";
        INFO ("UnGzipped file = $dcom_file");
}
elsif ($infile =~ /\.zip$/) {
        $dcom_file =~ s/\.zip$//;
	unzip $infile => $dcom_file or die "unzip failed: $UnzipError\n";
        INFO ("UnZipped file = $dcom_file");
}

my $fname = basename $dcom_file;
$enrfile = "${outdir}/${fname}.enr";
$arcfile = "${arcdir}/${fname}.enr";

my $grpHead = `head $dcom_file`;	#get 4 heaaders
my @arrHead = split /^/, $grpHead;	#split at start of line
my $fileHeader1 = $arrHead[0];
my $fileHeader2 = $arrHead[1];
my $fileHeader3 = $arrHead[2];
my $fileHeader4 = $arrHead[3];

# validate headers
if ($fileHeader1 !~ /^\#Created on/ig) {
	dpExit(1,"Missing header or header does not match to what is expected");
}
elsif ($fileHeader2 !~ /^\#Generated by WIP Extractor/ig) {
	dpExit(1,"Missing header or header does not match to what is expected");
}
elsif ($fileHeader3 !~ /^\#DataSource\,FormatVersion\,Lot\,Fab\,ProductFamily\,Technology\,Plan\,Product\,CustomerProduct\,SourceLot\,LotLabel\,LotType\,WaferNumber\,Wafer\,OperSequence\,ProcStep\,Stage\,OrigSlot\,FinalSlot\,OrigCass\,FinalCass\,Zone\,ZoneSeat\,ZoneBoat\,Subtool\,Equipment\,TrackInTime\,TrackOutTime\,Recipe\,Operator\,Tooling\,ReworkCount$/ig) {

	dpExit(1,"Missing header or header does not match to what is expected");	
}
elsif ($fileHeader4 !~ /^\#Version Number/ig) {
	dpExit(1,"Missing header or header does not match to what is expected");
}
else {
	INFO("Good! Header found.");
}

my $ln_cnt =  0;
my %lotHash;
open FH, $dcom_file or die "Can't read input file: $dcom_file $!";
while(my $line = <FH>) {
	$ln_cnt++;
	chomp $line;
	my @arr = split /\,/, $line; 
	my $ecnt = scalar @arr;

	if ($ln_cnt >= 5) {
		if ($ecnt == 33) {
			my $lot = trim($arr[2]);
			my $lottype = trim($arr[11]);
			my $customerproduct = trim($arr[8]);
			
			if ($customerproduct eq "NA") {
				my @dummy = split /\./, ($arr[7]);
				$customerproduct = substr $dummy[0], -7;
				$customerproduct = ${customerproduct}."-FAB";
			}
			$lotHash{$lot}{lottype} = $lottype;
			$lotHash{$lot}{custprod} = $customerproduct;
		}
		else {
			dpExit(1,"Data count does not match to the header at line $ln_cnt.");
		}
	}	
}
close (FH);

# get meta for each lot
my %enrMeta;
if ( !keys %lotHash ) {
	dpExit(1,"Zero data collected.");
}
else {
	foreach my $lot ( keys %lotHash ) {
		my %lotg = getLotInfoFromLotG("http://lotg.onsemi.com:60034/LotGWS/resources/lotg/lot/${lot}/sourceLot");
		#my $dwplm = getDWPlm->getPlmPartIdMetaData($lotg{Lot}{SearchedLotPart});
		#my $dwplm = getDWPlm->getPlmPartIdMetaData($lotg{Lot}{WaferPart});
		my $dwplm = getDWPlm->getPlmPartIdMetaData($lotHash{$lot}{custprod});
		my $onLotType = mapEfkOnLotType($lotHash{$lot}{lottype});	
		$onLotType = repNA($onLotType);
   	
		my $pti4 = $dwplm->{pti4};
		my $family = "";
		my @meta = ();

		if ($pti4 ne "") {
			 $family = substr($pti4, 0 ,2);
			 $family = repNA($family);
		}
		else {
			$family = repNA($family);
			$pti4 = repNA($pti4);
		}

		my $technology = repNA($dwplm->{technology});
		my $process = repNA($dwplm->{process});
		#my $lotclass = repNA($lotg{Lot}{LotClass});
		my $lotclass = "N/A";
		#my $prodcode = repNA($lotg{Lot}{WaferPart});
		my $prodcode = repNA($lotHash{$lot}{custprod});
		my $maskset = repNA($dwplm->{fab_mask});
		 
		push @meta, $process;
		push @meta, $technology;
		push @meta, $family;
		push @meta, $onLotType;
		push @meta, $fab;
		push @meta, $pti4;
		push @meta, $lotclass;
		push @meta, $prodcode;
		push @meta, $maskset;
		$enrMeta{$lot} = \@meta;
	}
}

#enrich file;
chomp $fileHeader1;
chomp $fileHeader2;
chomp $fileHeader3;
chomp $fileHeader4;

my $newHeader = $fileHeader3.","."OnProcess".","."OnTechnology".","."OnFamily".","."OnLotType".","."OnFabCode".","."OnPti4".","."OnLotClass".","."OnProductCode".","."OnMaskset";

$ln_cnt = 0;
my $fle_cnt = 1;

INFO ("Output file = ${enrfile}${fle_cnt}");
INFO ("Archive file = ${arcfile}${fle_cnt}");

open my $in, '<',  $dcom_file or die "Can't read input file: $dcom_file $!";
open my $out, '>', $enrfile.$fle_cnt or die "Can't write to new file: $!";
open my $out2, '>', $arcfile.$fle_cnt or die "Can't write to new file: $!";

print $out $newHeader,"\n";
print $out2 $newHeader,"\n";

while(my $line = <$in>) {
	$ln_cnt++;
	next if $line =~ /^\#/ig;
	my @arr = split /\,/, $line;
	my $ecnt = scalar @arr;

	my $lot = trim($arr[2]);
	my $custprod = trim($arr[8]);

	if ($custprod eq "NA") {
		my @dummy = split /\./, ($arr[7]);
		$custprod = substr $dummy[0], -7;			
		$arr[8] = ${custprod}."-FAB";
	}
	
	chomp $line;
	my $lnStr = join '|', @arr;
	$lnStr =~ s/\"//g;
	$lnStr =~ s/\n//g;
	$lnStr =~ s/\r//g;
	$lnStr =~ s/.*[^[:print:]]+//;
	my $enrStr = join '|',  @{$enrMeta{$lot}};

	print $out $lnStr.$enrStr,"\n";
	print $out2 $lnStr.$enrStr,"\n";

	if ($ln_cnt % $lnCntSplit == 0 ) {

                close($out);

                $fle_cnt++;

		INFO ("Output file = ${enrfile}${fle_cnt}");
		INFO ("Output2 file = ${arcfile}${fle_cnt}");

                my $ln_cnt2 = 0;

                open $out , '>', $enrfile.$fle_cnt or die "Can't write to split file:$!";
		open $out2 , '>', $arcfile.$fle_cnt or die "Can't write to split file:$!";

	        $ln_cnt2++;
		
                print $out $newHeader,"\n";
		print $out2 $newHeader,"\n";
               	print $out $lnStr.$enrStr,"\n" if $ln_cnt2 >= 1;
		print $out2 $lnStr.$enrStr,"\n" if $ln_cnt2 >= 1;
        }


}
close $out;
close $out2;

if ($hOptions{GZIP} ) {

	INFO("Compressing enriched file(a).");
	
	for(my $i = 1; $i <= $fle_cnt; $i++){
		my $gz_enrfile = "${arcfile}${i}.gz";
		system "gzip -fv ${arcfile}${i}";
	
		if ( -e $gz_enrfile ) {
			INFO("Compressed file succesfully = $gz_enrfile");
		}
		else {
			WARN("Compression failed.");
		}
	}
} 

# delete residue extracted files
unlink $dcom_file if $infile =~ /\.zip/i;


dpExit(0);

sub mapEfkOnLotType {
	my $efkLotType = shift;
	$efkLotType = trim($efkLotType);
	my $onLotType = $efkLotType;

	if ($efkLotType == 6) {
		$onLotType = "NS";
	}
	elsif ($efkLotType == 5) {
		$onLotType = "NS";
	}
	elsif ($efkLotType == 8) { 
		$onLotType = "PN";
	}
	elsif ($efkLotType == 0) {
                $onLotType = "PS";
        }
	if ($efkLotType eq "E") {
                $onLotType = "NS";
        }
	elsif ($efkLotType eq "G") {
                $onLotType = "NS";
        }
	elsif ($efkLotType eq "D") {
                $onLotType = "PS";
        }

	return $onLotType;
	
}
