#
# FSC Perl STDF Libraries
#
# Confidential Property of Fairchild Semiconductor Corperation
# (c) Copyright Fairchild Semiconductor Corperation, 2010
# All rights reserved
#
# MODIFICATION HISTORY:
#
# DATE       WHO             DESCRIPTION
# __________ ______________  __________________________________________________
# 04-08-2010 Scott Boothby   Original.

#
#  STDF PLUS V104 
#  Hand Coded stdf routines
#  These routines may duplicatve functionaly and
#  over-ride routines generated by stdf_gen
#

#
# note that gdrV4.pl and gdrPL.pl may be copies of each other or linked
# data structures below are specific to gdr for this version
#
@GDR_unpack_types = (
'B*0',
'U*1',
'U*2',
'U*4',
'I*1',
'I*2',
'I*4',
'R*4',
'R*8',
'Invalid_gdr_type',  # 9 does not exist in specification
'C*n',
'B*n' ) ;
# Types 12 and 13 are valid for V4

%GDR_pack_types = (
'B*0'=>0,
'U*1'=>1,
'U*2'=>2,
'U*4'=>3,
'I*1'=>4,
'I*2'=>5,
'I*4'=>6,
'R*4'=>7,
'R*8'=>8,
'Invalid_gdr_type'=>9,  # 9 does not exist in specification
'C*n'=>10,
'B*n'=>11) ;
# Types 12 and 13 are valid for V4

require "gdrPL.pl" ;

return(1) ;
