#
# FSC Perl STDF Libraries
#
# Confidential Property of Fairchild Semiconductor Corperation
# (c) Copyright Fairchild Semiconductor Corperation, 1999
# All rights reserved
#
# MODIFICATION HISTORY:
#
# DATE       WHO             DESCRIPTION
# __________ ______________  __________________________________________________
# 11-02-1999 Steve Frampton  Original.  Contact Information:
#                            (207) 273-3364
#                            sframpto@fairchildsemi.com,
#                            sframpto@midcoast.com
# 02-08-2000 Steve Frampton  Deleted primitive types as they were
#                            defined elsewhere
#                            Allow truncated PTR records near OPT_FLAG
#                            field.
# 02-15-2000 Steve Frampton  Added checks for Infinity
# 02-21-2000 Steve Frampton  Added function to update EMIR counts.
#                            pack_PTR updates PTR.REC_LEN
# 10-17-2000 Steve Frampton  Changed defaults for VCC, VEE, FREQ, LOAD_VAL to
#                            -999.
#                            Changed defaults for TEMP to -273
# 01-02-2001 Steve Frampton  Added pack_WMR and unpack_WMR to deal with record
#                            overflow with WMR records.
#                            WMR records are always written with a terminating
#                            die_count=0 record.
#                            Logical WMR record may include multiple physical
#                            WMR records.
# 03-09-2001 Steve Frampton  Fixed a number of bad hash dereferences
#                            EMIR.RESULT was packing as 0
#                            Don't even know how it ever worked before
# 03-15-2001 Steve Frampton  Removed direct reference to $out:: namespace
# 03-31-2006 Steve Frampton  Added check for environment Variable:
#                            %ENV{STDF_PERL_TRUN_PTR}
#                            Truncates PTR after result field if set.
#                            Developer should not populate fields after result field.
#                            Performance enhancement

#
#  STDF+
#  Hand Coded stdf routines
#  These routines may duplicatve functionaly and
#  over-ride routines generated by stdf_gen
#

#
# update_EMIR
#
# Function to update EMIR record
# Users responsibility to make sure that record is same length
# Checks are made and reported.
#
# File being updated must be closed
#
use POSIX ("close","write") ;  # ?? open
sub update_EMIR
{
my $emir=shift ;    # reference to emir record
my $out_fn=shift ;  # actual file name
my $rec_len = 0 ;

my $emir_bin = &pack_EMIR($emir) ;

{
local *EMIR_INPUT ;
my $status ;
my $rec_typ ;
my $rec_sub ;
my $buf ;
my $stdf_ver ;
if (! open EMIR_INPUT, "<$out_fn")
  {
  &::wlog(0,"update_EMIR:  Could not open $out_fn\n") ;
  return(-2) ;
  }
binmode EMIR_INPUT ;
($status, $rec_len, $rec_typ, $rec_sub, $buf) = &::read_first_rec( \*EMIR_INPUT, $stdf_ver ) ;
close EMIR_INPUT ;
my $len = length($emir_bin) ;
if (${$emir}{rec_len} != $rec_len)
  {
  &::wlog(0,"update_EMIR:  Could not update EMIR, record lengths don't match; file=$rec_len, update=$len \n") ;
  return(-1) ;
  }
}

if (! ($output=POSIX::open($out_fn, &POSIX::O_RDWR)))
  {
  &::wlog(0,"update_EMIR:  Could not open $out_fn for update_EMIR\n") ;
  return(-2) ;
  }

if (! POSIX::write($output, $emir_bin, length($emir_bin)))
  {
  &::wlog(0,"update_EMIR:  Could not write EMIR counts\n") ;
  return(-3) ;
  }

if ( ! POSIX::close( $output ))
  {
  &::wlog(0,"update_EMIR:  Could not POSIX::close $out_fn \n") ;
  return(-3) ;
  }

return(0) ;
}

#
# Alternate init values for PTR
# Truncate PTR records after results
# Base on default init

${init{'ptr_trun'}{rec_len}}=${init{ptr}{rec_len}} ;
${init{'ptr_trun'}{rec_typ}}=${init{ptr}{rec_typ}} ;
${init{'ptr_trun'}{rec_sub}}=${init{ptr}{rec_sub}} ;
${init{'ptr_trun'}{test_num}}=${init{ptr}{test_num}} ;
${init{'ptr_trun'}{head_num}}=${init{ptr}{head_num}} ;
${init{'ptr_trun'}{site_num}}=${init{ptr}{site_num}} ;
${init{'ptr_trun'}{test_flg}}=${init{ptr}{test_flg}} ;
${init{'ptr_trun'}{parm_flg}}=${init{ptr}{parm_flg}} ;
${init{'ptr_trun'}{result}}=${init{ptr}{result}} ;

#
# If defined by environment, truncate default PTR
#

($ENV{STDF_PERL_TRUN_PTR}) && ($stdf_perl_trun_ptr=$ENV{STDF_PERL_TRUN_PTR}) ;

if ($stdf_perl_trun_ptr)
	{
	%{$init{ptr}} = %{$init{ptr_trun}} ;
	}


#
# pack_PTR
#
# Same interface and similar functionality of routine generated by stdf_gen
# run with stdfPL.spec.  Intended to over-ride stdf_gen pack_PTR 
# routine.
#
# Record is assumed to be only truncated at option_flg or just after option_flg
# stdf_gen will truncate anywhere field is not defined.
#
# Performance enhancement. Ptr's are bulk of datalog file.
# In line code and minimized pack calls for speed.
#
# Not as much error checking as pack_PTR from stdf_gen
#
sub pack_PTR
{
my $ptr = shift ;
my $header ;
my $record ;
#
# convert $test_flg to B*1
#
my $num_of_pad_bits ; # variable, gets reused
my $test_flg =  $$ptr{test_flg} ;
$test_flg =~ s/^0+// ; # strip off leading sig bits of 0
$num_of_pad_bits = 8-length($test_flg) ;
($num_of_pad_bits >= 0 ) || confess_pack("ptr{test_flg} bit overflow\n" );
$test_flg = "0"x$num_of_pad_bits . $test_flg ;
#
# convert $parm_flg to B*1
#
my $parm_flg = $$ptr{parm_flg} ;
$parm_flg =~ s/^0+// ; # strip off leading sig bits of 0
$num_of_pad_bits = 8-length($parm_flg) ;
($num_of_pad_bits >= 0 ) || confess_pack("ptr{parm_flg} bit overflow\n" );
$parm_flg = "0"x$num_of_pad_bits . $parm_flg ;
#
# check result for infinity
# and Fix
#
my $result = $$ptr{'result'} ;
  (($result eq '-Infinity')
    || ($result eq '-NaN')
    || ($result eq '-1.#INF' )
    || ($result < $::FLT_MAX_NEG_CHECK ))
    && ($result = -$::FLT_MAX) ;
  ((${$ptr}{result} eq 'Infinity')
    || ($result eq 'NaN')
    || ($result eq '1.#INF' )
    || ($result > $::FLT_MAX_POS_CHECK ))
    && ($result = $::FLT_MAX) ;

$record = pack(
  $::U4.$::U1.$::U1.$::B1.$::B1.$::R4,
  ${$ptr}{test_num},
  ${$ptr}{head_num},
  ${$ptr}{site_num},
  $test_flg,
  $parm_flg,
  $result) ;

#
# truncate ptr if opt_flag is not defined
# or if %ENV{STDF_PERL_TRUN_PTR} is set
#
if (defined($$ptr{opt_flag}) && !$stdf_perl_trun_ptr)
  {
  #
  # convert $opt_flg to B*1
  #
  my $opt_flg = $$ptr{opt_flag} ;
  $opt_flg =~ s/^0+// ; # strip off leading sig bits of 0
  $num_of_pad_bits = 8-length($opt_flg) ;
  ($num_of_pad_bits >= 0 ) || confess_pack("ptr{opt_flg} bit overflow\n" );
  $opt_flg = "0"x$num_of_pad_bits . $opt_flg ;
  $record .= pack(
    $::B1,
    $opt_flg) ;
  if (defined($$ptr{res_scal}))
    {
    #
    # convert $desc_flg to B*1
    #
    my $desc_flg = $$ptr{desc_flg} ;
    $desc_flg =~ s/^0+// ; # strip off leading sig bits of 0
    $num_of_pad_bits = 8-length($desc_flg) ;
    ($num_of_pad_bits >= 0 ) || confess_pack("ptr{desc_flg} bit overflow\n" );
    $desc_flg = "0"x$num_of_pad_bits . $desc_flg ;

    #
    # find the length of all the strings C*n
    #
    $test_nam = $$ptr{test_nam} ;
    $test_nam =~ s/ +$// ; # remove trailing spaces
    ( length($test_nam) > 255 ) && ($test_nam = substr($test_nam,0,254)) ;
    $test_nam_len = length( $test_nam ) ;

    $seq_nam = $$ptr{seq_name} ;
    $seq_nam =~ s/ +$// ; # remove trailing spaces
    ( length($seq_nam) > 255 ) && ($seq_nam = substr($seq_nam,0,254)) ;
    $seq_nam_len = length( $seq_nam ) ;

    $test_txt = $$ptr{test_txt} ;
    $test_txt =~ s/ +$// ; # remove trailing spaces
    ( length($test_txt) > 255 ) && ($test_txt = substr($test_txt,0,254)) ;
    $test_txt_len = length( $test_txt ) ;
    
    #
    # check R*4s for Infinity -Infinity and fix
    #
    my $lo_limit = $$ptr{lo_limit} ;
      (($lo_limit eq '-Infinity')
        || ($lo_limit eq '-NaN')
        || ($lo_limit eq '-1.#INF' )
        || ($lo_limit < $::FLT_MAX_NEG_CHECK ))
        && ($lo_limit = -$::FLT_MAX) ;
    my $hi_limit = $$ptr{hi_limit} ;
      (($hi_limit eq 'Infinity')
        || ($hi_limit eq 'NaN')
        || ($hi_limit eq '1.#INF' )
        || ($hi_limit > $::FLT_MAX_POS_CHECK ))
        && ($hi_limit = $::FLT_MAX) ;

    $record .= pack(
    $::I1.$::U1.$::U1.$::B1.$::C7.$::I1.$::I1.$::U1.$::U1.$::U1.$::U1.$::R4.$::R4.$::U1.$::C.$test_nam_len.$::U1.$::C.$seq_nam_len.$::U1.$::C.$test_txt_len,
    $$ptr{res_scal},
    $$ptr{res_ldig},
    $$ptr{res_rdig},
    $desc_flg,
    $$ptr{units},
    $$ptr{llm_scal},
    $$ptr{hlm_scal},
    $$ptr{llm_ldig},
    $$ptr{llm_rdig},
    $$ptr{hlm_ldig},
    $$ptr{hlm_rdig},
    $lo_limit,
    $hi_limit,
    $test_nam_len,
    $test_nam,
    $seq_nam_len,
    $seq_nam,
    $test_txt_len,
    $test_txt ) ;
    }
  }
$$ptr{rec_len} = length($record) ;
$header = pack ( $::U2.$::U1.$::U1,
  $$ptr{rec_len},
  15,
  10);
  
return($header . $record) ;
}

$stdf_max_wmr_physical_die_bins = 32000 ;	# set equal to STDF_MAX_WMR_PHYSICAL_DIE_BINS in C libraries (used by edbtdl)
$stdf_max_wmr_die_bins = 256000 ;			# set equal to STDF_MAX_WMR_DIE_BINS in C libraries (used by edbtdl)

sub unpack_WMR
{
my $record = shift ;
my $wmr = shift ;
my $i = 0 ;
my $rc ;
my $len = length($$record) ;

undef($$wmr{rec_len});
undef($$wmr{rec_typ});
undef($$wmr{rec_sub});
undef($$wmr{die_cnt});
undef($$wmr{die_bin});

do
  {
  $rc = &::stdf_unpack(
    \'U*2 U*1 U*1 I*2',
    $record,
    \$i,
    \$$wmr{rec_len},
    \$$wmr{rec_typ},
    \$$wmr{rec_sub},
    \$$wmr{die_cnt});
  $$wmr{die_bin} .= substr($$record,$i,$$wmr{die_cnt}) ;
  $i += $$wmr{die_cnt} ;  # increment pointer
  } while ($i < $len) ;

$$wmr{die_cnt} = length($$wmr{die_bin}) ;
return (0) ;
}

#
# takes die_bin as a string, or an array of numbers >0 < 255
#
sub pack_WMR
{
my $wmr = shift ;
my $header ;
my $record='' ;
my $rec_len ;

my $wmr_die_bin ;

if ( $$wmr{die_bin} =~ /^ARRAY[(].*[)]$/ )
  {
  #
  # if die_bin is an array, convert it to a string
  # probably faster for user to do this
  # this is mostly for the use of stdf_copy_ascii
  #
  my $die ;
  my $i=0 ;
  foreach $die ( @{$$wmr{die_bin}} )
    {
    (($die < 256) && ($die >= 0 )) ||
      (&::wlog(0,"Warning:  pack_WMR:  WMR.DIE_BIN[$i]=$die, out of bounds\n")) ;
    $wmr_die_bin .= pack("C",$die) ;
    $i++ ;
    }
  }
else
  {
  $wmr_die_bin = $$wmr{die_bin} ;
  }

$$wmr{die_cnt} = length($wmr_die_bin) ;
my $die_cnt = $$wmr{die_cnt} ;

while ( $die_cnt > 0 )
  {
  if ( $die_cnt > $stdf_max_wmr_physical_die_bins )
    {
    #
    # We have greater than 32k wafer data left to write
    #
    $rec_len = $stdf_max_wmr_physical_die_bins + 2 ;
    $record .= pack( $::U2.$::U1.$::U1.$::I2,
                   $rec_len,
	           105,
	           200,
                   $stdf_max_wmr_physical_die_bins)
                  .substr($wmr_die_bin,0,$stdf_max_wmr_physical_die_bins) ;
		  $wmr_die_bin = substr($wmr_die_bin,$stdf_max_wmr_physical_die_bins) ;
		  $die_cnt = $die_cnt - $stdf_max_wmr_physical_die_bins ;
    }
  else
    {
    #
    # We have less than 32k wafer data left to write
    #
    $rec_len = $die_cnt + 2 ;
    $record .= pack( $::U2.$::U1.$::U1.$::I2,
                   $rec_len,
	           105,
	           200,
                   $die_cnt)
                   .$wmr_die_bin ;
    $len = length($wmr_die_bin) ;
    if ( $die_cnt !=  $len )
      {
      &::wlog(0,"pack_WMR:  error:  die_count left over = $die_cnt, map data left over len(map_data) = $len\n") ;
      }
    $die_cnt = 0 ;
    }
  }
#
# null terminating WMR record with 0 die count
# STDF+ Version >= 202
#
$record .= pack( $::U2.$::U1.$::U1.$::I2,
                     2, 
                   105,
                   200,
                   0) ;
return($record) ;
}

sub write_ascii_WMR 
{
my $wmr = shift ;
my $file = shift ;
my $record_number = shift ;
my @die_bin = split('',$$wmr{die_bin}) ;
my $die_bin ;
my $i=0 ;
print $file "\tWMR :\tREC_LEN=", $$wmr{rec_len},"\n" ;
print $file "\t\tREC_NO=", $record_number, "\n" ;
print $file "\t\tREC_TYP=", $$wmr{rec_typ}, "\n" ;
print $file "\t\tREC_SUB=", $$wmr{rec_sub}, "\n" ;
print $file "\t\tDIE_CNT=", $$wmr{die_cnt}, "\n" ;
my $j ;
for ($j=0; $j <= $#die_bin ; $j++ )
  {
  print $file "\t\tDIE_BIN[$j]=",unpack('C',$die_bin[$j]),"\n" ;
  }
print $file "\n\n" ;
}

#
# note that gdrV4.pl and gdrPL.pl may be copies of each other or linked
# data structures below are specific to gdr for this version
#
@GDR_unpack_types = (
'B*0',
'U*1',
'U*2',
'U*4',
'I*1',
'I*2',
'I*4',
'R*4',
'R*8',
'Invalid_gdr_type',  # 9 does not exist in specification
'C*n',
'B*n' ) ;
# Types 12 and 13 are valid for V4 

%GDR_pack_types = (
'B*0'=>0,
'U*1'=>1,
'U*2'=>2,
'U*4'=>3,
'I*1'=>4,
'I*2'=>5,
'I*4'=>6,
'R*4'=>7,
'R*8'=>8,
'Invalid_gdr_type'=>9,  # 9 does not exist in specification
'C*n'=>10,
'B*n'=>11) ;
# Types 12 and 13 are valid for V4 


require "gdrPL.pl" ;

return(1) ;
