#
# FSC Perl STDF Libraries
#
# Confidential Property of Fairchild Semiconductor Corperation
# (c) Copyright Fairchild Semiconductor Corperation, 1999
# All rights reserved
#
# MODIFICATION HISTORY:
#
# DATE       WHO             DESCRIPTION
# __________ ______________  __________________________________________________
# 11-02-1999 Steve Frampton  Original.  Contact Information:
#                            (207) 273-3364
#                            sframpto@fairchildsemi.com,
#                            sframpto@midcoast.com
# 02-08-1999 Steve Frampton  Moved unpack_PTR function to
#                            stdfV4_no_vms.pl since it does
#                            not support real conversions.
#                            This file is only loaded conditionally.
#                            Moved primitive types to stdf_unpack
#                            so that they may be shared.
#                            Added gdr.pl
# 05-01-2001 David Fletcher  Copied stdfV4.pl to stdfV3.pl

#
#  STDF V3
#  Hand Coded stdf routines
#  These routines may duplicatve functionaly and
#  over-ride routines generated by stdf_gen
#

#
# Only load this module if no real vms conversions are involved
#
if ( ! $main::vms_conversion )
  {
  require "stdfV4_no_vms.pl" ;
  }
#
# note that gdrV4.pl and gdrPL.pl may be copies of each other or linked
#
require "gdrV4.pl" ;

return(1) ;
