#
# FSC Perl STDF Libraries
#
# Confidential Property of Fairchild Semiconductor Corperation
# (c) Copyright Fairchild Semiconductor Corperation, 1999
# All rights reserved
#
# MODIFICATION HISTORY:
#
# DATE       WHO             DESCRIPTION
# __________ ______________  __________________________________________________
# 02-08-2000 Steve Frampton  Original.  Contact Information:
#                            (207) 273-3364
#                            sframpto@fairchildsemi.com,
#                            sframpto@midcoast.com
# 02-15-2000 Steve Frampton  Added Checks for Infinity
#

#
#  STDF V4
#  Hand Coded stdf routines
#  These routines duplicate functionaly and
#  over-ride routines generated by stdf_gen.
#  Conversions to VMS formats not supported.
#  If conversions to VMS are  desired, use
#  functions generated by stdf_gen.
#

#
# unpack_PTR
#
# Same interface and functionality of routine generated by stdf_gen
# run with stdfV4.spec.  Intended to over-ride stdf_gen unpack_PTR 
# routine.
#
# Performance enhancement. Ptr's are bulk of datalog file.
# In line code for speed.
#
# Not as much error checking as unpack_PTR from stdf_gen
#
# Does not support VMS conversions
#
sub unpack_PTR
{
my $record = shift ;
my $ptr = shift ;

#
# Check for VMS conversion requirements
# VMS not supported here
# $vms_conversion should be set prior to calling this routine
#
($main::vms_conversion)
  && confess(wlog( 0, "VMS conversions for V4 unpack_PTR not supported here.  Use unpack_PTR from stdf_gen instead\n")) ;
# 
# Byte ordering is controlled when data is unpacked
# Indices must be set up before calling this routine
#
# $::U2_0 $::U2_1
# $::U4_0 $::U4_1 $::U4_2 $::U4_3
# $::R4_0 $::R4_1 $::R4_2 $::R4_3
#
# Initialize fields as undefined
#
undef(${$ptr}{rec_len});
undef(${$ptr}{rec_typ});
undef(${$ptr}{rec_sub});
undef(${$ptr}{test_num});
undef(${$ptr}{head_num});
undef(${$ptr}{site_num});
undef(${$ptr}{test_flg});
undef(${$ptr}{parm_flg});
undef(${$ptr}{result});
undef(${$ptr}{test_txt});
undef(${$ptr}{alarm_id});
undef(${$ptr}{opt_flag});
undef(${$ptr}{res_scal});
undef(${$ptr}{llm_scal});
undef(${$ptr}{hlm_scal});
undef(${$ptr}{lo_limit});
undef(${$ptr}{hi_limit});
undef(${$ptr}{units});
undef(${$ptr}{c_resfmt});
undef(${$ptr}{c_llmfmt});
undef(${$ptr}{c_hlmfmt});
undef(${$ptr}{lo_spec});
undef(${$ptr}{hi_spec});
#
# Start Unpacking
#
  my $i=0 ;  # index into ${$record}
  my $bufflen = length(${$record}) ;  # length of data including header
  my @_U2 ;
  # header
  ($_U2[$::U2_0], $_U2[$::U2_1] , 
    ${$ptr}{rec_typ},
    ${$ptr}{rec_sub})
    = unpack($::U2s.$::U1.$::U1, substr(${$record},$i,4) ) ;
  ${$ptr}{rec_len} = unpack($::U2,pack($::U2s, @_U2)) ;
  $i += 4 ;
  # test_num
  ($bufflen-$i < 4) && return(0) ;
  my @_U4 ;
  ($_U4[$::U4_0], $_U4[$::U4_1], $_U4[$::U4_2], $_U4[$::U4_3])
    = unpack($::U4s, substr(${$record},$i,4) ) ; 
  ${$ptr}{test_num} = unpack($::U4,pack($::U4s, @_U4)) ;
  $i += 4 ;
  # head_num
  ($bufflen-$i < 1) && return(0) ;
  (${$ptr}{head_num})
    = unpack($::U1, substr(${$record},$i,1) ) ; 
  $i += 1 ;
  # site_num
  ($bufflen-$i < 1) && return(0) ;
  (${$ptr}{site_num})
    = unpack($::U1, substr(${$record},$i,1) ) ; 
  $i += 1 ;
  # test_flg
  ($bufflen-$i < 1) && return(0) ;
  (${$ptr}{test_flg})
    = unpack($::B1, substr(${$record},$i,1) ) ; 
  $i += 1 ;
  # parm_flg
  ($bufflen-$i < 1) && return(0) ;
  (${$ptr}{parm_flg})
    = unpack($::B1, substr(${$record},$i,1) ) ; 
  $i += 1 ;
  # result
  my @_R4 ;
  ($bufflen-$i < 4) && return(0) ;
  ($_R4[$::R4_0], $_R4[$::R4_1], $_R4[$::R4_2], $_R4[$::R4_3])
    = unpack($::R4s, substr(${$record},$i,4) ) ;
  ${$ptr}{result} = unpack($::R4,pack($::R4s, @_R4)) ;
  ((${$ptr}{result} eq '-Infinity')
    || (${$ptr}{result} eq '-NaN')
    || (${$ptr}{result} eq '-1.#INF' )
    || (${$ptr}{result} < $::FLT_MAX_NEG_CHECK ))
    && (${$ptr}{result} = -$::FLT_MAX) ;
  ((${$ptr}{result} eq 'Infinity')
    || (${$ptr}{result} eq 'NaN')
    || (${$ptr}{result} eq '1.#INF' )
    || (${$ptr}{result} > $::FLT_MAX_POS_CHECK ))
    && (${$ptr}{result} = $::FLT_MAX) ;
  $i += 4 ;
  # test_txt
  ($bufflen-$i < 1) && return(0) ;
  my $len = unpack($::U1,substr(${$record},$i,1)) ;
  $i +=1 ;
  ($bufflen-$i < $len) && return(0) ;
  ${$ptr}{test_txt} = substr(${$record},$i,$len) ;
  ${$ptr}{test_txt} =~ s/ +$// ; # remove trailing spaces
  $i += $len ;
  # alarm_id
  ($bufflen-$i < 1) && return(0) ;
  $len = unpack($::U1,substr(${$record},$i,1)) ;
  $i +=1 ;
  ($bufflen-$i < $len) && return(0) ;
  ${$ptr}{alarm_id} = substr(${$record},$i,$len) ;
  ${$ptr}{alarm_id} =~ s/ +$// ; # remove trailing spaces
  $i += $len ;
  # opt_flag
  ($bufflen-$i < 1) && return(0) ;
  (${$ptr}{opt_flag})
    = unpack($::B1, substr(${$record},$i,1) ) ; 
  $i += 1 ;
  # res_scal
  ($bufflen-$i < 1) && return(0) ;
  (${$ptr}{res_scal})
    = unpack($::I1, substr(${$record},$i,1) ) ; 
  $i += 1 ;
  # llm_scal
  ($bufflen-$i < 1) && return(0) ;
  (${$ptr}{llm_scal})
    = unpack($::I1, substr(${$record},$i,1) ) ; 
  $i += 1 ;
  # hlm_scal
  ($bufflen-$i < 1) && return(0) ;
  (${$ptr}{hlm_scal})
    = unpack($::I1, substr(${$record},$i,1) ) ; 
  $i += 1 ;
  # lo_limit
  ($bufflen-$i < 4) && return(0) ;
  ($_R4[$::R4_0], $_R4[$::R4_1], $_R4[$::R4_2], $_R4[$::R4_3])
    = unpack($::R4s, substr(${$record},$i,4) ) ;
  ${$ptr}{lo_limit} = unpack($::R4,pack($::R4s, @_R4)) ;
  # No check for Infinity - lets hope they get that right
  ((${$ptr}{lo_limit} eq '-Infinity')
    || (${$ptr}{lo_limit} eq '-NaN')
    || (${$ptr}{lo_limit} eq '-1.#INF' )
    || (${$ptr}{lo_limit} < $::FLT_MAX_NEG_CHECK ))
    && (${$ptr}{lo_limit} = -$::FLT_MAX) ;
  $i += 4 ;
  # hi_limit
  ($bufflen-$i < 4) && return(0) ;
  ($_R4[$::R4_0], $_R4[$::R4_1], $_R4[$::R4_2], $_R4[$::R4_3])
    = unpack($::R4s, substr(${$record},$i,4) ) ;
  ${$ptr}{hi_limit} = unpack($::R4,pack($::R4s, @_R4)) ;
  # No check for -Infinity - lets hope they get that right
  ((${$ptr}{hi_limit} eq 'Infinity')
    || (${$ptr}{hi_limit} eq 'NaN')
    || (${$ptr}{hi_limit} eq '1.#INF' )
    || (${$ptr}{hi_limit} > $::FLT_MAX_POS_CHECK ))
    && (${$ptr}{hi_limit} = $::FLT_MAX) ;
  $i += 4 ;
  # units
  ($bufflen-$i < 1) && return(0) ;
  my $len = unpack($::U1,substr(${$record},$i,1)) ;
  $i +=1 ;
  ($bufflen-$i < $len) && return(0) ;
  ${$ptr}{units} = substr(${$record},$i,$len) ;
  ${$ptr}{units} =~ s/ +$// ; # remove trailing spaces
  $i += $len ;
  # c_resfmt
  ($bufflen-$i < 1) && return(0) ;
  my $len = unpack($::U1,substr(${$record},$i,1)) ;
  $i +=1 ;
  ($bufflen-$i < $len) && return(0) ;
  ${$ptr}{c_resfmt} = substr(${$record},$i,$len) ;
  ${$ptr}{c_resfmt} =~ s/ +$// ; # remove trailing spaces
  $i += $len ;
  # c_llmfmt
  ($bufflen-$i < 1) && return(0) ;
  my $len = unpack($::U1,substr(${$record},$i,1)) ;
  $i +=1 ;
  ($bufflen-$i < $len) && return(0) ;
  ${$ptr}{c_llmfmt} = substr(${$record},$i,$len) ;
  ${$ptr}{c_llmfmt} =~ s/ +$// ; # remove trailing spaces
  $i += $len ;
  # c_hlmfmt
  ($bufflen-$i < 1) && return(0) ;
  my $len = unpack($::U1,substr(${$record},$i,1)) ;
  $i +=1 ;
  ($bufflen-$i < $len) && return(0) ;
  ${$ptr}{c_hlmfmt} = substr(${$record},$i,$len) ;
  ${$ptr}{c_hlmfmt} =~ s/ +$// ; # remove trailing spaces
  $i += $len ;
  # lo_spec
  ($bufflen-$i < 4) && return(0) ;
  ($_R4[$::R4_0], $_R4[$::R4_1], $_R4[$::R4_2], $_R4[$::R4_3])
    = unpack($::R4s, substr(${$record},$i,4) ) ;
  ${$ptr}{lo_spec} = unpack($::R4,pack($::R4s, @_R4)) ;
  # No check for Infinity - lets hope they get that right
  ((${$ptr}{lo_spec} eq '-Infinity')
    || (${$ptr}{lo_spec} eq '-NaN')
    || (${$ptr}{lo_spec} eq '-1.#INF' )
    || (${$ptr}{lo_spec} < $::FLT_MAX_NEG_CHECK ))
    && (${$ptr}{lo_spec} = -$::FLT_MAX) ;
  $i += 4 ;
  # hi_spec
  ($bufflen-$i < 4) && return(0) ;
  ($_R4[$::R4_0], $_R4[$::R4_1], $_R4[$::R4_2], $_R4[$::R4_3])
    = unpack($::R4s, substr(${$record},$i,4) ) ;
  ${$ptr}{hi_spec} = unpack($::R4,pack($::R4s, @_R4)) ;
  # No check for -Infinity - lets hope they get that right
  ((${$ptr}{hi_spec} eq 'Infinity')
    || (${$ptr}{hi_spec} eq 'NaN')
    || (${$ptr}{hi_spec} eq '1.#INF' )
    || (${$ptr}{hi_spec} > $::FLT_MAX_POS_CHECK ))
    && (${$ptr}{hi_spec} = $::FLT_MAX) ;
  $i +=4 ;
return (0) ;
}


return (1) ;
